# Generated by Django 2.2 on 2019-05-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30)),
                ('district_2011', models.CharField(max_length=30)),
                ('old_survey_vdc_name_2011', models.CharField(max_length=100)),
                ('old_survey_vdc_code_2011', models.CharField(max_length=30)),
                ('old_ward_no_2011', models.PositiveSmallIntegerField()),
                ('old_survey_ward_code_2011', models.CharField(max_length=30)),
                ('province', models.PositiveSmallIntegerField()),
                ('new_district_2018', models.CharField(max_length=30)),
                ('cbs_district_code_2018', models.PositiveSmallIntegerField()),
                ('category_of_lu_2018', models.CharField(max_length=50)),
                ('lu_name_2018', models.CharField(max_length=100)),
                ('lu_full_name_2018', models.CharField(max_length=200)),
                ('lu_name_nepali_2018', models.CharField(max_length=200)),
                ('cbs_lu_code_2018', models.PositiveIntegerField()),
                ('lu_ward_no_2018', models.PositiveSmallIntegerField()),
                ('cbs_lu_ward_code_2018', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('vdc_muni', models.CharField(max_length=300)),
                ('old_ward_no', models.PositiveSmallIntegerField()),
                ('province', models.PositiveSmallIntegerField()),
                ('cbs_district_code', models.PositiveSmallIntegerField()),
                ('category_of_lu', models.CharField(max_length=50)),
                ('lu_name', models.CharField(max_length=100)),
                ('lu_full_name', models.CharField(max_length=200)),
                ('lu_name_nepali', models.CharField(max_length=200)),
                ('lu_hlcit_code', models.CharField(max_length=30)),
                ('lu_cbs_code', models.PositiveIntegerField()),
                ('new_ward_no', models.PositiveSmallIntegerField()),
                ('cbs_ward_code', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
