# Generated by Django 2.2 on 2019-05-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map2011',
            name='old_survey_ward_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
